# ????, ?? ??????? ???????? Gateway
server.port=8080

# URL ????????? ??????? (Server), ???? Gateway ????? ????? ???????
# ???? ?????????? ????? Docker, ????????? ??? ???????: http://shareit-server:9090
shareit-server.url=http://localhost:9090

# ???????????
logging.level.org.springframework.web=INFO
